### ISSUE TITLE
Not connecting to the default bootnodes in chainspec during initial sync

### ISSUE THREAD

**Issue by Curu24** [AvaProtocol/OAK-blockchain#525]
After migrating Turing node, we couldn't sync the chain from scratch due to inability to connect to any peers.

-  tried both --chain turing and download the spec file from github https://raw.githubusercontent.com/AvaProtocol/OAK-blockchain/master/node/res/turing.json
-  tried different binary versions like 2.1.4, 2.0.0, 1.7.0

here's the systemd service file we're using:

```
ExecStart=/usr/local/bin/turing \
  --name Polkadotters \
  --base-path '/var/lib/turing' \
  --wasm-execution Compiled \
  --chain turing \
  --collator \
  --force-authoring \
  --trie-cache-size 0 \
  -- \
  --state-pruning 100 \
  --blocks-pruning 100
```
  
  Finally we managed to resolve this issue with the help of fellow collator (props to Sik | crifferent.de) who made a bootnode to connect to.

**Comment by jonathanudd** [comment]
Was this fixed? After restarting a Turing node it cannot connect to any of the bootnodes in the chainspec found here https://raw.githubusercontent.com/AvaProtocol/OAK-blockchain/refs/heads/master/node/res/turing.json

**Comment by jonathanudd** [comment]
We have one other node as well and I added it as a bootnode which worked and the node started syncing.
I then removed the manually added bootnode again and now it can connect to one of the bootnodes in the spec file.

**Comment by Curu24** [comment]
> We have one other node as well and I added it as a bootnode which worked and the node started syncing. I then removed the manually added bootnode again and now it can connect to one of the bootnodes in the spec file.

Looks like it is working now. I can start syncing from scratch now.
